# Generated by Django 5.0.4 on 2024-05-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='is_published',
        ),
        migrations.AddField(
            model_name='character',
            name='fraction',
            field=models.CharField(choices=[('outers', 'Внешний мир'), ('resistance', 'Сопротивление'), ('neutrals', 'Нейтральные персонажи'), ('domination', 'Волшебное Превосходство'), ('moon', 'Луна')], default='neutrals', max_length=100, verbose_name='Фракция'),
        ),
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
