# Generated by Django 5.0.4 on 2024-05-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_character_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='fraction',
            new_name='faction',
        ),
        migrations.AlterField(
            model_name='character',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/core/images/%Y/%m/%d/'),
        ),
    ]
