# Generated by Django 5.0.4 on 2024-05-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_fraction_character_faction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['time_create']},
        ),
        migrations.RemoveIndex(
            model_name='character',
            name='core_charac_time_cr_05de75_idx',
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['time_create'], name='core_charac_time_cr_59b3f0_idx'),
        ),
    ]
