# Generated by Django 5.1.1 on 2024-10-14 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subforum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('News', 'News'), ('Characters', 'Characters'), ('Episodes', 'Episodes'), ('References', 'References'), ('Production', 'Production'), ('bugs', 'Bugs')], default=1, max_length=32, verbose_name='Название')),
                ('slug', models.SlugField(default='News', editable=False)),
            ],
            options={
                'verbose_name': 'Разделы форума',
                'verbose_name_plural': 'Разделы форума',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(default='', max_length=32)),
                ('name', models.CharField(default='', max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('bio', models.TextField(default='Write a couple of words about yourself', max_length=500)),
                ('avatar', models.ImageField(blank=True, default=None, max_length=255, upload_to='')),
                ('status', models.CharField(blank=True, default='', max_length=25)),
                ('slug', models.SlugField()),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('Y', 'Youkai'), ('B', 'Beast'), ('H', 'Helicopter Apache')], default='H', max_length=32, verbose_name='Пол')),
                ('reputation', models.IntegerField(default=0, verbose_name='Репутация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, unique=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=models.SET('deleted'), related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель темы')),
                ('subforum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subforum', to='forum.subforum', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Обсуждения',
                'verbose_name_plural': 'Обсуждения',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000, verbose_name='Текст')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('author', models.ForeignKey(on_delete=models.SET('deleted'), related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='forum.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Комментарии',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created'],
            },
        ),
    ]
