# Generated by Django 5.1.1 on 2024-10-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_subforum_profile_topic_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
