# Generated by Django 5.1.1 on 2024-10-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=25, unique=True),
        ),
    ]
